In [49]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import Adam,SGD
import numpy as np

#学習データ
X = np.array([[1]],dtype=np.float32)
y = np.array([[2]],dtype=np.float32)

#学習データを増やす
# X = np.array([[1],[2]],dtype=np.float32)
# y = np.array([[2],[4]],dtype=np.float32)

#学習データを増やす
# X = np.array([[1],[2],[4],[5]],dtype=np.float32)
# y = np.array([[2],[4],[8],[10]],dtype=np.float32)

#学習データの精度が低い
# X = np.array([[1],[2],[4],[5]],dtype=np.float32)
# y = np.array([[2],[4],[7],[10]],dtype=np.float32)

#モデル
model = Sequential()
model.add(Dense(1))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='SGD')

#学習
for i in range(200):
    model.fit(X, y, batch_size=1, epochs=1, verbose=0)
    print()
    print(i+1,"回目")
    print(np.round(model.predict(X), decimals=2))
    print()

#予測
print("----------------------------------------------")
print("未知データ＝　",np.round(model.predict(np.array([[1501]],dtype=np.float32))))


1 回目
[[1.5 ]
 [2.96]
 [5.87]
 [7.33]]


2 回目
[[1.59]
 [3.15]
 [6.27]
 [7.83]]


3 回目
[[1.62]
 [3.23]
 [6.44]
 [8.05]]


4 回目
[[1.57]
 [3.11]
 [6.2 ]
 [7.74]]


5 回目
[[1.7 ]
 [3.33]
 [6.59]
 [8.21]]


6 回目
[[1.66]
 [3.28]
 [6.51]
 [8.13]]


7 回目
[[1.61]
 [3.21]
 [6.4 ]
 [7.99]]


8 回目
[[ 2.27]
 [ 4.39]
 [ 8.64]
 [10.77]]


9 回目
[[ 2.41]
 [ 4.69]
 [ 9.26]
 [11.54]]


10 回目
[[1.77]
 [3.51]
 [6.97]
 [8.71]]


11 回目
[[ 2.27]
 [ 4.4 ]
 [ 8.68]
 [10.81]]


12 回目
[[ 2.22]
 [ 4.36]
 [ 8.65]
 [10.79]]


13 回目
[[1.69]
 [3.41]
 [6.83]
 [8.55]]


14 回目
[[1.69]
 [3.37]
 [6.75]
 [8.44]]


15 回目
[[ 2.33]
 [ 4.55]
 [ 8.98]
 [11.2 ]]


16 回目
[[1.81]
 [3.55]
 [7.03]
 [8.77]]


17 回目
[[1.64]
 [3.23]
 [6.42]
 [8.01]]


18 回目
[[ 2.21]
 [ 4.3 ]
 [ 8.47]
 [10.56]]


19 回目
[[1.89]
 [3.68]
 [7.26]
 [9.05]]


20 回目
[[1.67]
 [3.27]
 [6.48]
 [8.08]]


21 回目
[[1.75]
 [3.4 ]
 [6.69]
 [8.34]]


22 回目
[[1.66]
 [3.28]
 [6.5 ]
 [8.12]]


23 回目
[[1.61]
 [3.17]
 [6.28]
 [7.83]]


24 回目
[[1.65]
 [3.27]
 [6.5 ]
 [8.12]]


